### ISSUE TITLE
Y tensioner idler - small range

### ISSUE THREAD

**Issue by ochm** [gregsaun/prusa_i3_bear_upgrade#103]
2.1 tensioner idler have small range for movement. I made small modification, range for open is now full.
[y_idler_tensioner-trimed-corner.zip](https://github.com/gregsaun/prusa_i3_bear_upgrade/files/4050683/y_idler_tensioner-trimed-corner.zip)
![IMG_1078](https://user-images.githubusercontent.com/47606742/72219581-ed652380-3547-11ea-96b6-ee183fab1318.jpg)
![IMG_1079](https://user-images.githubusercontent.com/47606742/72219582-ed652380-3547-11ea-83fe-0d7f2510ea0d.jpg)

**Comment by gregsaun** [comment]
This was made on purpose mainly for those two reasons :
  - Due to the pivot point you change the position of the belt (on the Z axis) while tensioning. It is currently designed to have a change of 0.03mm which is lower than belt tolerance and printed part tolerance. However, if y a user is opening too much the tensioner it could create too much difference in the position of the belt.
  - too much opening will make the idler less stiff and might become fragile
