### ISSUE TITLE
Update to MK3S+ Y Rod Holder

### ISSUE THREAD

**Issue by spooknik** [gregsaun/prusa_i3_bear_upgrade#124]
Hello! 

Just getting first getting into this project. I noticed you're still using the older style of Y-Rod holder with the Z-ties. Prusa has updated them for the MK3S+ to have screws. I don't see any functional difference but might look a bit nicer aesthetically. 

Do you have plans to update to the latest and would you welcome a PR if I had a go at it? 

Thanks for the cool project 👍 

Regards,
Spooknik 

Edit: for reference they look like[ this.](https://cdn.help.prusa3d.com/wp-content/uploads/2021/01/e51efae750ffd4d4_painted-1536x1152.jpeg)

**Comment by gregsaun** [comment]
Hi spooknik, I don't like those MK3S+ rod holders because you have to re-align the smooth rods everytime you have to do maintenance (on original MK3 as well). To me zipties are a better idea. You can find some mods on Thingi and co that are using two screws to maintain the rods if you prefer.

**Comment by spooknik** [comment]
Thanks for the quick reply. Good point about the maintenance. I'll stick with the zipties for now. As I said for me it was mostly an  aesthetics thing. I can always "upgrade" later on if needed. 

Please close the issue if it suits you :)

**Comment by taz43mca** [comment]
I built one over a year ago. Used zip ties and have seen no reason to do otherwise.

Sent from the all new AOL app for Android 
 
  On Mon, Sep 13, 2021 at 4:54 AM, ***@***.***> wrote:   


Hello!

Just getting first getting into this project. I noticed you're still using the older style of Y-Rod holder with the Z-ties. Prusa has updated them for the MK3S+ to have screws. I don't see any functional difference but might look a bit nicer aesthetically.

Do you have plans to update to the latest and would you welcome a PR if I had a go at it?

Thanks for the cool project 👍
 
Regards,
Spooknik

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
