### ISSUE TITLE
PSU lower mount

### ISSUE THREAD

**Issue by serkanaksu** [gregsaun/prusa_i3_bear_upgrade#96]
I‘ve got self adjusting V-Slot Nuts. When I try to fix the PSU lower mount I can‘t fix it because of the missing V-Slot overhang (if it’s called so).

**Comment by gregsaun** [comment]
Could you share a link of the t-nut you are using? What lower PSU mount are you using (MK2S, MK2.5(S), MK3(S) grey PSU or MK3(S) black PSU)?

**Comment by serkanaksu** [comment]
MK3S silver PSU with the original Prusa Cover.
These are the T-Nuts I'm using.

![61vwgTFo91L _SL1200_](https://user-images.githubusercontent.com/7974223/68382080-4339db80-0153-11ea-926a-c8353f6e24e5.jpg)

It would be nice, if the mount would have the V-Slot profile.

**Comment by gregsaun** [comment]
Are you using this mount?
https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/dev/printed_parts/mk3_mk3s/stl/psu_lower_mount_silver.stl

**Comment by serkanaksu** [comment]
Correct!

**Comment by gregsaun** [comment]
This PSU mount does not have the vslot alignment tab because some PSU cover are not reliable. For example, some MK2S came with injection molded cover which are not precise at all. Not having the vslot alignment tab makes it easier to adjust for such cases.

Those t-nuts will not work if you have the alignment tab printed because it will collide with the center of the t-nuts.

**Comment by serkanaksu** [comment]
I will try to build a custom one :)

**Comment by gregsaun** [comment]
Please share what you design, interested to see your idea!

I agree for the PSU cover, for now you can check what there is in the optional parts from the community.

**Comment by taz43mca** [comment]
I looked at the 2.1 Alfa and did download the mount. Am waiting for the final of 2.1 before I commit to final assembly. Also. after 3 successful prints last night, after replacing all Y axis rods and bearings, my print tonight had a 1-2 mm shift at about 20mm height (z). I guess that was not the problem. Plenty of grease and no marks on rods. The problem is elsewhere. Any thoughts???
In a message dated 11/8/2019 7:48:15 AM Eastern Standard Time, notifications@github.com writes:


Are you using this mount?
https://github.com/gregsaun/prusa_i3_bear_upgrade/blob/dev/printed_parts/mk3_mk3s/stl/psu_lower_mount_silver.stl
